{% set name = "jill" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jill-{{ version }}.tar.gz
  sha256: d9f969823f1e23975ad7335189fc7d577bd8f11bb164f9a39bf1b92405618aab

build:
  entry_points:
    - jill=jill.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core
    - poetry
  run:
    - fire <0.6.0,>=0.5.0
    - jsonschema >=4.17.3
    - python >=3.7
    - python-gnupg >=0.5.0
    - requests >=2.28.2
    - requests-futures >=1.0.0
    - semantic_version >=2.10.0
    - python-wget >=3.2

test:
  imports:
    - jill
  commands:
    - pip check
    - jill --help
    - jill install nightly --confirm
  requires:
    - pip

about:
  home: https://github.com/johnnychen94/jill.py
  summary: JILL -- Julia Installer for Linux (MacOS, Windows and FreeBSD) -- Light
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mkitti
    - ngam
