{% set name = "jill" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jill-{{ version }}.tar.gz
  sha256: 885bb1c26e2ac6563828767eb87409dd69581e5f187110b958f4c7dcbe45b27b

build:
  entry_points:
    - jill=jill.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fire
    - jsonschema
    - python >=3.6
    - python-gnupg
    - requests
    - requests-futures
    - semantic_version
    - python-wget

test:
  imports:
    - jill
  commands:
    - pip check
    - jill --help
    - jill install nightly --confirm
  requires:
    - pip

about:
  home: https://github.com/johnnychen94/jill.py
  summary: JILL -- Julia Installer for Linux (MacOS, Windows and FreeBSD) -- Light
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mkitti
    - ngam
